server:
  port: 9083
datasource1:
  jdbc-url: jdbc:postgresql://192.168.5.69:5432/Test
  username: postgres
  password: postgres
  driver-class-name: org.postgresql.Driver
#Êý¾Ý¿â2
datasource2:
  jdbc-url: jdbc:postgresql://192.168.5.69:5432/Test_2
  username: postgres
  password: postgres
  driver-class-name: org.postgresql.Driver